## This input file is to work with waveform_parser.py 
# Example:
#Waveform_File_Path         C:\Users\jiangongwei\Documents\Python_data\waveform_tr72603.txt
#Col_Time                0
#Col_Waveform            1
#Waveform_Analysis_Bin_Flor  0.788
#Waveform_Analysis_Bin_Step  0.005
#Waveform_Analysis_Bin_Ceil  0.813


Waveform_File_Path          C:\Users\jiangongwei\Documents\Python_data\waveform_tr72603.txt
Col_Time                    0
Col_Waveform                1 
Waveform_Analysis_Bin_Flor  0.728
Waveform_Analysis_Bin_Step  0.005
Waveform_Analysis_Bin_Ceil  0.813